Repository LArSoft/larreco, pull requests merged in 2020-03, with the labels that each got.

#1 TrajCluster and ClusterAna module improvements
  larreco/Calorimetry/Calorimetry_module.cc
  larreco/ClusterFinder/ClusterTrackAna_module.cc
  larreco/ClusterFinder/TrajCluster_module.cc
  larreco/ClusterFinder/cluster_microboone.fcl
  larreco/ClusterFinder/clustermodules.fcl
  larreco/Genfit/GeaneMCApplication.cxx
  larreco/Genfit/GeaneMCApplication.h
  larreco/RecoAlg/TCAlg/DataStructs.cxx
  larreco/RecoAlg/TCAlg/DataStructs.h
  larreco/RecoAlg/TCAlg/DebugStruct.h
  larreco/RecoAlg/TCAlg/PFPUtils.cxx
  larreco/RecoAlg/TCAlg/PFPUtils.h
  larreco/RecoAlg/TCAlg/StepUtils.cxx
  larreco/RecoAlg/TCAlg/StepUtils.h
  larreco/RecoAlg/TCAlg/TCCR.cxx
  larreco/RecoAlg/TCAlg/TCHist.cxx
  larreco/RecoAlg/TCAlg/TCHist.h
  larreco/RecoAlg/TCAlg/TCShower.cxx
  larreco/RecoAlg/TCAlg/TCShower.h
  larreco/RecoAlg/TCAlg/TCTruth.cxx
  larreco/RecoAlg/TCAlg/TCTruth.h
  larreco/RecoAlg/TCAlg/TCVertex.cxx
  larreco/RecoAlg/TCAlg/TCVertex.h
  larreco/RecoAlg/TCAlg/Utils.cxx
  larreco/RecoAlg/TCAlg/Utils.h
  larreco/RecoAlg/TrajClusterAlg.cxx
  larreco/RecoAlg/TrajClusterAlg.h
  larreco/RecoAlg/clusteralgorithms.fcl
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started

#8 Calculate wire pitch for the correct plane. This bug fix was implememted but removed accidentally.
  larreco/Calorimetry/Calorimetry_module.cc
Labels: L1-pending, L2-approved, code-checks-approved, fully-signed, tests-started

#9 Change some services to SHARED
  larreco/Calibrator/IPhotonCalibratorService.h
  larreco/Calibrator/PhotonCalibratorServiceStandard.h
  larreco/ClusterFinder/Cluster3D_module.cc
  larreco/HitFinder/HitAnaModule_module.cc
  larreco/RecoAlg/CMTool/CMTAlgMatch/CFAlgoChargeDistrib.cxx
  larreco/RecoAlg/CMTool/CMTAlgMatch/CFAlgoTimeProf.cxx
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, requires-external, tests-started
